apiVersion: v1
kind: Namespace
metadata:
  name: trillian-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-mysql
  namespace: trillian-system
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-logserver
  namespace: trillian-system
  annotations:
    {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    sigstore.app/component: "trillian-logsigner"
    sigstore.app: trillian
  name: trillian-logsigner
  namespace: trillian-system
  annotations:
    {}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-mysql
  namespace: trillian-system
type: Opaque
data:
  mysql-root-password: "Y2hhbmdlbWVub3c="
  mysql-password: "Y2hhbmdlbWU="
  mysql-user: "bXlzcWw="
  mysql-database:  "dHJpbGxpYW4="
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-mysql
  namespace: trillian-system
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "5Gi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-mysql
  namespace: trillian-system
spec:
  ports:
    - name: 3306-tcp
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  type: "ClusterIP"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    sigstore.app/component: "trillian-logserver"
    sigstore.app: trillian
  name: trillian-logserver
  namespace: trillian-system
spec:
  ports:
    - name: 8091-tcp
      port: 8091
      protocol: TCP
      targetPort: 8091
    - name: 8090-tcp
      port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    sigstore.app/component: "trillian-logserver"
    sigstore.app: trillian
  type: "ClusterIP"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    sigstore.app/component: "trillian-logsigner"
    sigstore.app: trillian
  name: trillian-logsigner
  namespace: trillian-system
spec:
  ports:
    - name: 8091-tcp
      port: 8091
      protocol: TCP
      targetPort: 8091
  selector:
    sigstore.app/component: "trillian-logsigner"
    sigstore.app: trillian
  type: "ClusterIP"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
  name: trillian-mysql
  namespace: trillian-system
spec:
  selector:
    matchLabels:
      sigstore.app/component: "mysql"
      sigstore.app: trillian
  replicas: 1
  strategy:
    type: Recreate
    rollingUpdate: null
  template:
    metadata:
      labels:
        sigstore.app/component: "mysql"
        sigstore.app: trillian
    spec:
      serviceAccountName: trillian-mysql
      containers:
        - name: trillian-mysql
          image: "gcr.io/trillian-opensource-ci/db_server@sha256:20a4b9b9532f466936ca2bb186251a0a21d34f89b78b12bb2bb1c2aae5e8e339"
          imagePullPolicy: "IfNotPresent"
          args:
            - --ignore-db-dir=lost+found
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trillian-mysql
                  key: mysql-root-password
            - name: MYSQL_USER
              value: "mysql"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trillian-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              value: trillian
          ports:            
            - containerPort: 3306
              protocol: TCP
          livenessProbe:
            exec:
              command:
              - /etc/init.d/mysql
              - status
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
              - /etc/init.d/mysql
              - status
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            {}
          volumeMounts:
            - name: storage
              mountPath: /var/lib/mysql
              subPath: 
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: trillian-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sigstore.app/component: "trillian-logserver"
    sigstore.app: trillian
  name: trillian-logserver
  namespace: trillian-system
spec:
  selector:
    matchLabels:
      sigstore.app/component: "trillian-logserver"
      sigstore.app: trillian
  replicas: 1
  template:
    metadata:
      labels:
        sigstore.app/component: "trillian-logserver"
        sigstore.app: trillian
    spec:
      serviceAccountName: trillian-logserver
      initContainers:
        - name: "wait-for-trillian-db"
          image: "docker.io/toolbelt/netcat@sha256:7d921b6d368fb1736cb0832c6f57e426c161593c075847af3378eb3185801cea"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until nc -z -w 10 trillian-mysql 3306; do echo waiting for trillian-mysql; sleep 5; done;"]
      containers:
        - name: trillian-trillian-logserver
          image: "gcr.io/projectsigstore/trillian_log_server@sha256:75dbbfc4c0b64334b985c4971fe58c30b9dd73d7aa54b15cee61223ff92aebf3"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--storage_system=mysql"
            - "--quota_system=mysql"
            - "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(MYSQL_HOSTNAME):$(MYSQL_PORT))/$(MYSQL_DATABASE)"
            - "--rpc_endpoint=0.0.0.0:8091"
            - "--http_endpoint=0.0.0.0:8090"
            - "--alsologtostderr"
          env:            
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-database
            - name: MYSQL_HOSTNAME
              value: trillian-mysql
            - name: MYSQL_PORT
              value: "3306"
          ports:            
            - containerPort: 8091
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
          resources:
            {}
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    sigstore.app/component: "trillian-logsigner"
    sigstore.app: trillian
  name: trillian-logsigner
  namespace: trillian-system
spec:
  selector:
    matchLabels:
      sigstore.app/component: "trillian-logsigner"
      sigstore.app: trillian
  replicas: 1
  template:
    metadata:
      labels:
        sigstore.app/component: "trillian-logsigner"
        sigstore.app: trillian
    spec:
      serviceAccountName: trillian-logsigner
      initContainers:
        - name: "wait-for-trillian-db"
          image: "docker.io/toolbelt/netcat@sha256:7d921b6d368fb1736cb0832c6f57e426c161593c075847af3378eb3185801cea"
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "until nc -z -w 10 trillian-mysql 3306; do echo waiting for trillian-mysql; sleep 5; done;"]
      containers:
        - name: trillian-trillian-logsigner
          image: "gcr.io/projectsigstore/trillian_log_signer@sha256:b56ed0b7b5e9813c91b208ba6041c9342f9a53162d96943374e59b5289090f1f"
          imagePullPolicy: "IfNotPresent"
          args:
            - "--storage_system=mysql"
            - "--quota_system=mysql"
            - "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(MYSQL_HOSTNAME):$(MYSQL_PORT))/$(MYSQL_DATABASE)"
            - "--rpc_endpoint=0.0.0.0:8091"
            - "--http_endpoint=0.0.0.0:8090"
            - "--force_master=true"
            - "--alsologtostderr"
          env:            
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                    name: trillian-mysql
                    key: mysql-database
            - name: MYSQL_HOSTNAME
              value: trillian-mysql
            - name: MYSQL_PORT
              value: "3306"
          ports:            
            - containerPort: 8091
              protocol: TCP
          resources:
            {}
      nodeSelector:
        kubernetes.io/arch: amd64
---
apiVersion: batch/v1
kind: Job
metadata:
  name: release-name-trillian-createdb
  namespace: trillian-system
  labels:
    sigstore.app/component: "mysql"
    sigstore.app: trillian
spec:
  ttlSecondsAfterFinished: 3600
  template:
    spec:
      serviceAccountName: trillian-logserver
      restartPolicy: Never
      automountServiceAccountToken: 
      containers:
        - name: release-name-trillian-createdb
          image: "ghcr.io/sigstore/scaffolding/createdb@sha256:9aa98492115c465b0cecfd6dbb04411a40c0d2d7e5d7c510f5646bd1d825e3c7"
          imagePullPolicy: "IfNotPresent"
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: trillian-mysql
                  key: mysql-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trillian-mysql
                  key: mysql-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: trillian-mysql
                  key: mysql-database
            - name: MYSQL_HOSTNAME
              value: trillian-mysql
            - name: MYSQL_PORT
              value: "3306"
            - name: EXIT_DIR
              value: "/var/exitdir"
          args: [
            "--db_name=$(MYSQL_DATABASE)",
            "--mysql_uri=$(MYSQL_USER):$(MYSQL_PASSWORD)@tcp($(MYSQL_HOSTNAME):$(MYSQL_PORT))/"
          ]
          volumeMounts:
            - name: exit-dir
              mountPath: "/var/exitdir"
      volumes:
        - name: exit-dir
          emptyDir: {}
